sudo: required

language: cpp

os:
  - linux

matrix:
  include:
    - env: BUILD_TYPE=Debug
      compiler: gcc
    - env: BUILD_TYPE=Release
      compiler: gcc
    - env: BUILD_TYPE=Debug
      compiler: clang
    - env: BUILD_TYPE=Release
      compiler: clang

branches:
  only:
    - master
    - /^(dev)|(dev_.*)$/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.7

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

before_script:
  - mkdir build && cd build
  - cmake -DTASTYLIB_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

script:
  - make -j
